client_config_backend: settings
client_config:
  client_id: 890897613670-i4pk0nu42ddrvvh1m3q3ed9t90u1pudb.apps.googleusercontent.com
  client_secret: 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

save_credentials: False
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install